apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-cnpg-vault-user
  namespace: postgresql-cnpg
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgresql-cnpg-vault-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: vault
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: databases/postgresql-cnpg
        property: VAULT_PASSWORD
